title: xxiwriterecipesnotlovelettersxx
description: vegan recipes for my emo friends
author: darcy
theme: minima
url: "https://xxiwriterecipesnotloveletters.github.io"
include:
  - assets/css/style.scss
